name = "kinexus"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "kinexus"
database_id = "cef3ca63-575e-44ee-ba8b-d7c120ca470f"
migrations_dir = "migrations"
